spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_branch_fetch_size: 1000
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false